---
title: "2027948 - RADAR AND LIDAR REMOTE SENSING"
subtitle: "Academic Year: 2025"
format: html
---
## PREREQUISITOS:
- Aprobación del curso *Percepción Remota*
- Aprobación del curso *Programación SIG*

## DESCRIPCIÓN DE LA ASIGNATURA:
::: {.callout-important collapse=false}
### OBJETIVOS:
-	Conocer los principios físicos asociados a  SAR y LiDAR 
-	Entender las características principales de los datos SAR y LiDAR
- Conocer los métodos de corrección radiométrica y geométrica de imágenes SAR
-	Obtener información temática a partir de imágenes SAR y datos LiDAR

### COMPETENCIAS GENÉRICAS: 
-	Comprensión de los fundamentos teóricos de la percepción remota SAR y LiDAR
-	Obtención de habilidades prácticas para seleccionar, procesar y analizar datos SAR y LiDAR
-	Desarrollo de pensamiento crítico sobre las ventajas y las limitaciones de estas tecnologías

### COMPETENCIAS ESPECÍFICAS:
- Entendimiento del flujo de trabajo genérico para el uso de datos SAR y LiDAR
- Adaptación y creación de scripts para  procesamiento y análisis de datos SAR y LiDAR
-	Evaluación de la calidad de productos de percepción remota SAR y LiDAR

### METODOLOGIA:
-	Lectura antes de la clase a cargo del estudiante
- Presentación de conceptos, métodos y técnicas a cargo del profesor
-	Realización de ejercicios conceptuales y prácticos a cargo  del estudiante

### SOFTWARE
-  *PARTE 1:* GEE, Python, Sentinel-1 Toolbox (S1TBX) 
-  *PARTE 2:* R, Python & Jupyter & Google Colaboratory
:::


## CONTENIDO DETALLADO 

::: {.callout-important collapse=true}

## PARTE 1 – RADAR DE APERTURA SINTETICA (SAR)

### Topic 1 - Principles of Radar Remote Sensing 

### Topic 2 - Basic processing of SAR images - SNAP

### Topic 3 – Propiedades radiativas de suelos y vegetación

### Topic 4 – Basic processing of SAR images - GEE 

### Topic 5 –  Analysis Ready SAR Data

### Topic 6 - SAR interferometry

:::

::: {.callout-important collapse=true}

## PARTE 2 – LIGHT DETECTION AND RANGING (LiDAR)

### Topic 7 – Introduction to LiDAR

Lecture: Chapter 1 of Wang et al. (2024)

Practical: https://snowex-2022.hackweek.io/tutorials/lidar/1_introduction_to_lidar.html

### Topic 8 – LiDAR Remote Sensing Principles

Lecture: Chapter 2 of Wang et al. (2024)

Practical: [Functionality of the lasR package](https://r-lidar.github.io/lasR/articles/tutorial.html)

### Topic 9  – LiDAR Data Acquisition 

Lecture: Chapter 3 of Wang et al. (2024)

Practical: https://www.opengeomatics.ca/LiDAR-acquisition-and-analysis.html

### Topic 10 -   LiDAR Data Processing 

Lecture: Chapter 4 of Wang et al. (2024)

### Topic 11 - Applications

Lecture: Chapter 5 of Wang et al. (2024)

:::

## EVALUACIÓN DEL CURSO: 

::: {.callout-important collapse=false}

-	Presentación de dos exámenes escritos sobre aspectos teóricos (50%)
    - Examen 1 - 25 de Septiembre
    - Examen 2 - 27 de Noviembre
-	Entrega de dos informes técnicos  (50%)
    - Informe 1 - 2 de Octubre
    - Informe 2 - 4 de Diciembre

:::

## BIBLIOGRAFIA

::: {.callout-important collapse=true}

Chollet, F. Deep Learning with Python [2nd ed.],  Manning, 2021. 504 pp.

De Grandi, G.D. et al. Spatial Analysis for Radar Remote Sensing of Tropical Forests, CRC Press, 2021. 380pp.

Flores-Anderson, A.I. et al. The Synthetic Aperture Radar (SAR) Handbook: Comprehensive Methodologies for Forest Monitoring and Biomass Estimation,  SERVIR GLOBAL & SilvaCarbon, 2019. 307 pp.

Frery, A.C. et al. SAR Image Analysis - A Computational Statistics Approach: With R Code, Data, and Applications, Wiley-IEEE Press, 2022. 208 pp.

Gao, W. et al. Deep Learning for 3D Point Clouds, Springer Verlag, 2025. 250 pp.

Kamusoko, C., Optical and SAR Remote Sensing of Urban Areas: A Practical Guide, Springer, 2021. 130 pp.

Liu, S. et al. 3D Point Cloud Analysis. Traditional, Deep Learning, and Explainable Machine Learning Methods, Springer, 2021. 146 pp.

Mandal, D. et al. Radar Remote Sensing for Crop Biophysical Parameter Estimation, Springer, 2021. 236 pp.

Poux, F. 3D Data Science with Python, O'Reilly Media, 2025. 500 pp.

Simms, E.L. SAR Image Interpretation for Various Land Covers – A Practical Guide. CRC Press, 2011. 376 pp. 

Wang Ch. et al. Introduction to LiDAR Remote Sensing.  CRC Press, 2024. 259 pp.

Yamaguchi, Y. Polarimetric SAR imaging: theory and applications. CRC Press, 2020. 350 pp.

:::
