---
title: "2027948 - RADAR AND LIDAR REMOTE SENSING"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# 📑 Course Brief

**Focus:** This course will focus on understanding the principles and applications of both Synthetic Aperture Radar (SAR) and LiDAR (Light Detection and Ranging).

**How:** reading,  learning by doing and writing

# 🎯 Learning Objectives

- The course aims to equip participants with a comprehensive understanding of both SAR and LiDAR techniques. 

- It will explore the unique capabilities and limitations of each technology. 

- Participants will learn how to process and analyze data from both SAR and LiDAR systems. 

- The course will emphasize  theory and application exercises of these technologies. 

# Class Atendance Policy

Students are expected to attend all classes. Occasional absences due to illness are considered excused. Participation in university activities must be requested in advance.

# Artificial Intelligence Policy

Students may use generative AI to support —not replace— their own thinking, effort, and style. In any case, the use of generative AI is permitted for up to 50% of the submitted work.

-----------------

**Select Academic Year/Term:**

<a href="2026/index.qmd">
    <button class="button-61">2026</button>
</a>

