---
title: "🗓️ Week 01 - Introduction, Context & Key Concepts"
---

In this first week, we will cover what you can expect to learn from this course and the course logistics: all you need to know about the structure of the lectures, classes, assessments, and how we will interact throughout this course. 

## 👨‍🏫 Lecture Slides 

Either click on the slide area below or click [here](slides.qmd) to view it in fullscreen.
Use your keypad to navigate the slides.

<div class="container" style="position: relative;overflow: hidden;width: 100%;min-height:600px;">
<iframe src="slides.html" style="position=absolute;top: 0;left: 0;bottom: 0;right: 0;width: 100%;min-height:600px;"></iframe>
</div>

🎥 

## ✍️ Coursework

🚧 Download  [ESA Sentinel Application Platform (SNAP)](https://step.esa.int/main/download/) 🚧

🚧 Follow the Sentinel-1 [SAR basics tutorial](https://drive.google.com/file/d/1fNTn9cwKorvMJgmv2FQtWOlmkqPesU6q/view) 🚧

👨‍🏫  For the tutorial, a Fine Quad Polarization SLC Radarsat-2 sample dataset covering the Wesenberg area in Germany is used. You can download it from [here](https://earth.esa.int/eogateway/ftp/missions/sample-data/third-party-missions/radarsat/RS2_OK153952_PK1408399_DK1372518_FQ17_20150626_052324_HH_VV_HV_VH_SLC.zip).

## 📚 Required Reading

Read [this document](https://media.wiley.com/product_data/excerpt/9X/11197952/111979529X-4.pdf) before next class. 

## 📟 Communication

- Get to know your peers in the course 

- Organize your study group 